name: boss-csv

on:
  workflow_dispatch

jobs:
  boss-csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r boss-csv/requirements.txt
    - run: python boss-csv/boss_csv.py
