name: boss-csv

on:
  workflow_dispatch:
    inputs:
      maxResults:
        description: 'Max results'     
        required: false
        default: '0'

jobs:
  boss-csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r boss-csv/requirements.txt
    - run: python boss-csv/boss_csv.py ${{ github.event.inputs.maxResults }}
    - uses: actions/upload-artifact@v3
      with:
        name: bosses.csv
        path: bosses.csv
